elastic:
  host: localhost
  port: 9200

spring:
  elasticsearch:
    uris: localhost:9200

logging:
  level:
    root: INFO
    co.kr.sizl: DEBUG
    org.springframework.data.elasticsearch.client.WIRE: trace

server:
  port: 4383
