elastic:
  host: 103.218.159.37
  port: 9200

spring:
  elasticsearch:
    uris: 103.218.159.37:9200

logging:
  level:
    com:
      example: debug
    sql: trace
    org:
      springframework:
        data:
          elasticsearch:
            core:
              ReactiveElasticsearchTemplate: trace
              ReactiveElasticsearchClient: trace
              ReactiveElasticsearchRestTemplate: trace

server:
  port: 4382
